name: Build TWRP

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y \
          git-core gnupg flex bison gperf build-essential \
          zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
          libncurses-dev libncurses6 lib32z1-dev libssl-dev \
          ccache libgl1-mesa-dev libxml2-utils xsltproc unzip openjdk-11-jdk python-is-python3

    - name: Install repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+rx ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize TWRP repo and sync
      run: |
        mkdir ~/twrp && cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        repo sync -j2

    - name: Add device tree and kernel source
      run: |
        cp -r $GITHUB_WORKSPACE/device ~/twrp/device
        git clone https://github.com/MotorolaMobilityLLC/kernel-msm.git ~/twrp/kernel/motorola/malmo

    - name: Build recovery
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch twrp_malmo-eng
        mka recoveryimage

    - name: Upload recovery.img
      uses: actions/upload-artifact@v4
      with:
        name: recovery
        path: ~/twrp/out/target/product/malmo/recovery.img
